pipeline{
    agent any
    tools{
        maven 'maven_build'
    }
    stages{
        stage('Build Maven'){
            steps{
                sh 'mvn clean install'
            }
        }
    }
}